routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('terminos', function () {
    return view('terminos');
});

Auth::routes();

Route::group(['middleware' => ['auth']], function () {
    Route::get('/home', 'HomeController@index')->name('home');

    Route::group(['prefix' => 'hoteles', 'as' => 'hoteles.'], function () {
        Route::get('/', 'HotelController@index')->name('index');
        Route::get('create', 'HotelController@create')->name('create');
        Route::post('/', 'HotelController@store')->name('store');
        Route::get('{hotel}', 'HotelController@show')->name('show');
        Route::get('{hotel}/edit', 'HotelController@edit')->name('edit');
        Route::put('{hotel}', 'HotelController@update')->name('update');
        Route::delete('{hotel}', 'HotelController@destroy')->name('destroy');

        Route::post('changeWorkingHotel', 'HotelController@changeWorkingHotel')->name('changeworkinghotel');
    });

    Route::group(['prefix' => 'habitaciones', 'as' => 'habitaciones.'], function () {
        Route::get('/', 'HabitacionesController@index')->name('index');
        Route::get('create', 'HabitacionesController@create')->name('create');
        Route::post('/', 'HabitacionesController@store')->name('store');
        Route::get('{habitacion}', 'HabitacionesController@show')->name('show');
        Route::get('{habitacion}/edit', 'HabitacionesController@edit')->name('edit');
        Route::put('{habitacion}', 'HabitacionesController@update')->name('update');
        Route::delete('{habitacion}', 'HabitacionesController@destroy')->name('destroy');
    });

    Route::group(['prefix' => 'huespedes', 'as' => 'huespedes.'], function () {
        Route::get('/', 'HuespedesController@index')->name('index');
        Route::get('create', 'HuespedesController@create')->name('create');
        Route::post('/', 'HuespedesController@store')->name('store');
        Route::get('{huesped}', 'HuespedesController@show')->name('show');
        Route::get('{huesped}/edit', 'HuespedesController@edit')->name('edit');
        Route::put('{huesped}', 'HuespedesController@update')->name('update');
        Route::delete('{huesped}', 'HuespedesController@destroy')->name('destroy');
    });

    Route::group(['prefix' => 'reservas', 'as' => 'reservas.'], function () {
        Route::get('/', 'ReservasController@index')->name('index');
        Route::get('create', 'ReservasController@create')->name('create');
        Route::post('/', 'ReservasController@store')->name('store');
        Route::get('{reserva}', 'ReservasController@show')->name('show');
        Route::get('{reserva}/edit', 'ReservasController@edit')->name('edit');
        Route::put('{reserva}', 'ReservasController@update')->name('update');
        Route::delete('{reserva}', 'ReservasController@destroy')->name('destroy');
    });

    Route::group(['prefix' => 'soporte', 'as' => 'soporte.'], function () {
        // DERIVACION DE CONVERSACIONES
            // EL DE ATENCION A CLIENTES DEBE ENTRAR A ESTA PANTALLA
            Route::get('chats/viewer', function () {
                return view('support.logform');
            })->name('index');

            Route::post('chats/viewer', 'BotFwrk\ConversationController@showChatLog')->name('show');
        // DERIVACION DE CONVERSACIONES
    });
});

// DERIVACION DE CONVERSACIONES
    // EL CLIENTE VE ESTA PANTALLA
    Route::get('hotel/soporte/{conversationId}', function ($conversationId) {
        return view('support.support')->with('conversationId', $conversationId);
    });
// DERIVACION DE CONVERSACIONES

app/Http/Controllers/HabitacionesController.php
<?php

namespace App\Http\Controllers;

use App\Models\Hotel\Habitacion;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;

class HabitacionesController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\Http\Response|\Illuminate\View\View
     */
    public function index()
    {
        if (session('selectedHotelId')){
            $habitaciones = Habitacion::with('estado')->where('hotel_id', session('selectedHotelId'))->get();

            return view('habitaciones.index', compact('habitaciones'));
        }

        return view('habitaciones.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\Http\Response|\Illuminate\View\View
     */
    public function create()
    {
        return view('habitaciones.crear');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\RedirectResponse|\Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'numero' => 'required|string',
            'extension_tel' => 'required|integer',
        ]);

        try {
            DB::beginTransaction();

            $habitacion = new Habitacion();

            $habitacion->hotel_id = session('selectedHotelId');
            $habitacion->extension_tel = $request->extension_tel;
            $habitacion->estado_habitacion_id = 1; // por defecto la habitacion nueva esta libre
            $habitacion->numero = $request->numero;

            $habitacion->save(); // The created_at and updated_at timestamps will automatically be set when the save method is called

            DB::commit();

            \Session::flash("success", "La habitación fue creada exitosamente.");
            return redirect()->route('habitaciones.show', [$habitacion]);
        } catch (\Exception $e) {
            DB::rollback();
            return redirect()->back()->withErrors($e->getMessage())->withInput();
        }
    }

    /**
     * Display the specified resource.
     *
     * @param Habitacion $habitacion
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\Http\Response|\Illuminate\View\View
     */
    public function show(Habitacion $habitacion)
    {
        return view('habitaciones.mostrar', compact('habitacion'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param Habitacion $habitacion
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\Http\Response|\Illuminate\View\View
     */
    public function edit(Habitacion $habitacion)
    {
        return view('habitaciones.editar', compact('habitacion'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @param Habitacion $habitacion
     * @return \Illuminate\Http\RedirectResponse|\Illuminate\Http\Response
     */
    public function update(Request $request, Habitacion $habitacion)
    {
        $this->validate($request, [
            'numero' => 'required',
            'extension_tel' => 'required|integer',
        ]);

        try {
            DB::beginTransaction();

            $habitacion->numero = $request->numero;
            $habitacion->extension_tel = $request->extension_tel;

            $habitacion->save(); // The created_at and updated_at timestamps will automatically be set when the save method is called

            DB::commit();

            \Session::flash("success", "La habitación fue editada exitosamente.");
            return redirect()->route('habitaciones.show', [$habitacion]);
        } catch (\Exception $e) {
            DB::rollback();
            return redirect()->back()->withErrors($e->getMessage())->withInput();
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param Habitacion $habitacion
     * @return \Illuminate\Http\RedirectResponse|\Illuminate\Http\Response
     */
    public function destroy(Habitacion $habitacion)
    {
        try {
            DB::beginTransaction();

            $habitacion->delete();

            DB::commit();

            \Session::flash("success", "La habitación fue borrada exitosamente.");
            return redirect()->route('habitaciones.index');
        } catch (\Exception $e) {
            DB::rollback();
            return redirect()->back()->withErrors($e->getMessage());
        }
    }
}

resources/views/habitaciones/crear.blade.php
@extends('layouts.project')

@section('htmlheader_title', "{$selectedHotel->nombre} | Crear nueva habitación")

@section('content_header_title')
    {{ $selectedHotel->nombre }}
@endsection

@section('content_header_description')
    Crear nueva habitación
@endsection

@section('main-content')
    <div class="row">
        <div class="col-md-10 col-md-offset-1">
            <form action="{{ route('habitaciones.store') }}" method="post" id="form_crear" name="form_crear">
                {{ csrf_field() }}
                <div class="form-group">
                    <label for="numero">Número Habitación</label>
                    <input type="text" class="form-control" id="numero" name="numero" placeholder="Número Habitación" value="{{ old('numero') }}">
                </div>
                <div class="form-group">
                    <label for="extension_tel">Ext. Telefónica</label>
                    <input type="text" class="form-control" id="extension_tel" name="extension_tel" placeholder="Ext. Telefónica" value="{{ old('extension_tel') }}">
                </div>

                <button type="submit" class="btn btn-success btn-lg btn-block">Crear</button>
                <a class="btn btn-info btn-xs btn-block" href="{{ route('habitaciones.index') }}" role="button">Retroceder</a>
            </form>
        </div>
    </div>
@endsection

resources/views/habitaciones/editar.blade.php
@extends('layouts.project')

@section('htmlheader_title', "{$selectedHotel->nombre} | Editar habitación {$habitacion->numero}")

@section('content_header_title')
    {{ $selectedHotel->nombre }}
@endsection

@section('content_header_description')
    Editar habitación <b>{{ $habitacion->numero }}</b>
@endsection

@section('main-content')
    <div class="row">
        <div class="col-md-10 col-md-offset-1">
            <form action="{{ route('habitaciones.update', [$habitacion]) }}" method="post" id="form_editar" name="form_editar">
                {{ method_field('PUT') }}
                {{ csrf_field() }}
                <div class="form-group">
                    <label for="numero">Número Habitación</label>
                    <input type="text" class="form-control" id="numero" name="numero" placeholder="Número Habitación" value="{{ old('numero', $habitacion->numero) }}">
                </div>
                <div class="form-group">
                    <label for="extension_tel">Ext. Telefónica</label>
                    <input type="text" class="form-control" id="extension_tel" name="extension_tel" placeholder="Ext. Telefónica" value="{{ old('extension_tel', $habitacion->extension_tel) }}">
                </div>
                <button type="submit" class="btn btn-success btn-block"><i class="fa fa-save"></i> Guardar</button>
                <a class="btn btn-info btn-xs btn-block" href="{{ route('habitaciones.show', [$habitacion]) }}" role="button">Retroceder</a>
            </form>
        </div>
    </div>
@endsection

resources/views/habitaciones/index.blade.php
@extends('layouts.project')

@section('htmlheader_title', 'Habitaciones')

@section('content_header_title')
    Habitaciones
@endsection

@section('content_header_description')
    Listado de habitaciones
@endsection

@section('main-content')
    @include('hoteles.partials.selector_lista_hoteles')

    @if(session('selectedHotelId'))
        <div class="box">
            <div class="box-header with-border">
                <h3 class="box-title">Habitaciones registradas en {{ $selectedHotel->nombre }}</h3>
                <div class="box-tools pull-right">
                    <a class="btn btn-primary" href="{{ route('habitaciones.create') }}" role="button" title="Crear habitación"><i class="fa fa-plus-circle"></i> Crear habitación</a>
                </div>
                <!-- /.box-tools -->
            </div>
            <div class="box-body">
                @if (count($habitaciones) > 0)
                    <div class="table-responsive">
                        <table id="data_table" name="data_table" class="table table-striped table-hover">
                            <thead>
                            <tr>
                                <th style="text-align: center;">Número Habitación</th>
                                <th style="text-align: center;">Estado Habitación</th>
                                <th style="text-align: center;">Extensión Tel.</th>
                                <th style="text-align: center;">&nbsp;</th>
                            </tr>
                            </thead>
                            <tbody>
                            @foreach($habitaciones as $habitacion)
                                <tr style="text-align: center;">
                                    <td style="text-align: center; vertical-align: middle;">
                                        {{ $habitacion->numero }}
                                    </td>
                                    <td style="text-align: center; vertical-align: middle;">
                                        {{ $habitacion->estado->nombre }}
                                    </td>
                                    <td style="text-align: center; vertical-align: middle;">
                                        {{ $habitacion->extension_tel }}
                                    </td>
                                    <td style="text-align: right; vertical-align: middle;">
                                        <div class="btn-group" role="group">
                                            {{--Ver Registro--}}
                                            <a class="btn btn-xs btn-primary" href="{{ route('habitaciones.show', [$habitacion]) }}" role="button" title="Ver Detalles"><i class="fa fa-folder-open-o"></i> Ver Detalles</a>
                                            {{-- Editar registro --}}
                                            <a class="btn btn-xs btn-warning" href="{{ route('habitaciones.edit', [$habitacion]) }}" role="button" title="Editar registro"><i class="fa fa-edit"></i> Editar registro</a>
                                            {{-- Borrar registro --}}
                                            <form class="btn-group" action="{{ route('habitaciones.destroy', [$habitacion]) }}" method="post" onsubmit="return confirm('Confirma la eliminación de este registro?');">
                                                {{ method_field('DELETE') }}
                                                {{ csrf_field() }}
                                                <button type="submit" class="btn btn-xs btn-danger" title="Borrar registro"><span class="glyphicon glyphicon-trash" aria-hidden="true"></span> Borrar registro</button>
                                            </form>
                                        </div>
                                    </td>
                                </tr>
                            @endforeach
                            </tbody>
                        </table>
                    </div>
                @else
                    <div class="alert alert-warning" role="alert" style="margin-top: 0; margin-bottom: 0;"><b>Aún no se han creado habitaciones en el hotel seleccionado</b></div>
                @endif
            </div><!-- /.box-body -->
            <div class="box-footer">
                <a class="btn btn-primary pull-right" href="{{ route('habitaciones.create') }}" role="button" title="Crear habitación"><i class="fa fa-plus-circle"></i> Crear habitación</a>
            </div><!-- box-footer -->
        </div><!-- /.box -->
    @else
        <div class="callout callout-info">
            <h4>Aviso</h4>
            <p>Debe seleccionar un hotel para poder ver el listado de habitaciones del mismo</p>
        </div>
    @endif
@endsection

resources/views/habitaciones/mostrar.blade.php
@extends('layouts.project')

@section('htmlheader_title', "{$habitacion->hotel->nombre} | Detalles de la habitación {$habitacion->numero}")

@section('content_header_title')
    {{ $habitacion->hotel->nombre }}
@endsection

@section('content_header_description')
    Detalles de la habitación {{ $habitacion->numero }}
@endsection

@section('main-content')
    <div class="row">
        <div class="col-md-10 col-md-offset-1">
            <div class="box">
                <div class="box-header with-border">
                    <h3 class="box-title">Datos básicos</h3>
                </div>
                <!-- /.box-header -->
                <div class="box-body">
                    <div class="form-group">
                        <label for="hotel_id">Hotel</label>
                        <input disabled type="text" class="form-control" id="hotel_id" name="hotel_id" value="{{ $habitacion->hotel->nombre }}">
                    </div>
                    <div class="form-group">
                        <label for="estado_habitacion_id">Estado</label>
                        <input disabled type="text" class="form-control" id="estado_habitacion_id" name="estado_habitacion_id" value="{{ $habitacion->estado->nombre }}">
                    </div>
                    <div class="form-group">
                        <label for="numero">Número</label>
                        <input disabled type="text" class="form-control" id="numero" name="numero" value="{{ $habitacion->numero }}">
                    </div>
                    <div class="form-group">
                        <label for="extension_tel">Ext. Telefónica</label>
                        <input disabled type="text" class="form-control" id="extension_tel" name="extension_tel" value="{{ $habitacion->extension_tel }}">
                    </div>
                </div>
                <!-- /.box-body -->
                <div class="box-footer">
                    <a class="btn btn-warning btn-block" href="{{ route('habitaciones.edit', [$habitacion]) }}" role="button"><i class="fa fa-edit"></i> Editar</a>
                    <a class="btn btn-info btn-xs btn-block" href="{{ route('habitaciones.index') }}" role="button">Retroceder</a>
                </div>
                <!-- box-footer -->
            </div>
            <!-- /.box -->
        </div>
    </div>
@endsection

{{--
@section('scripts')
    @parent
    <script>
        $(function() {

        });
    </script>
@endsection
--}}