routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('terminos', function () {
    return view('terminos');
});

Auth::routes();

Route::group(['middleware' => ['auth']], function () {
    Route::get('/home', 'HomeController@index')->name('home');

    Route::group(['prefix' => 'hoteles', 'as' => 'hoteles.'], function () {
        Route::get('/', 'HotelController@index')->name('index');
        Route::get('create', 'HotelController@create')->name('create');
        Route::post('/', 'HotelController@store')->name('store');
        Route::get('{hotel}', 'HotelController@show')->name('show');
        Route::get('{hotel}/edit', 'HotelController@edit')->name('edit');
        Route::put('{hotel}', 'HotelController@update')->name('update');
        Route::delete('{hotel}', 'HotelController@destroy')->name('destroy');

        Route::post('changeWorkingHotel', 'HotelController@changeWorkingHotel')->name('changeworkinghotel');
    });

    Route::group(['prefix' => 'habitaciones', 'as' => 'habitaciones.'], function () {
        Route::get('/', 'HabitacionesController@index')->name('index');
        Route::get('create', 'HabitacionesController@create')->name('create');
        Route::post('/', 'HabitacionesController@store')->name('store');
        Route::get('{habitacion}', 'HabitacionesController@show')->name('show');
        Route::get('{habitacion}/edit', 'HabitacionesController@edit')->name('edit');
        Route::put('{habitacion}', 'HabitacionesController@update')->name('update');
        Route::delete('{habitacion}', 'HabitacionesController@destroy')->name('destroy');
    });

    Route::group(['prefix' => 'huespedes', 'as' => 'huespedes.'], function () {
        Route::get('/', 'HuespedesController@index')->name('index');
        Route::get('create', 'HuespedesController@create')->name('create');
        Route::post('/', 'HuespedesController@store')->name('store');
        Route::get('{huesped}', 'HuespedesController@show')->name('show');
        Route::get('{huesped}/edit', 'HuespedesController@edit')->name('edit');
        Route::put('{huesped}', 'HuespedesController@update')->name('update');
        Route::delete('{huesped}', 'HuespedesController@destroy')->name('destroy');
    });

    Route::group(['prefix' => 'reservas', 'as' => 'reservas.'], function () {
        Route::get('/', 'ReservasController@index')->name('index');
        Route::get('create', 'ReservasController@create')->name('create');
        Route::post('/', 'ReservasController@store')->name('store');
        Route::get('{reserva}', 'ReservasController@show')->name('show');
        Route::get('{reserva}/edit', 'ReservasController@edit')->name('edit');
        Route::put('{reserva}', 'ReservasController@update')->name('update');
        Route::delete('{reserva}', 'ReservasController@destroy')->name('destroy');
    });

    Route::group(['prefix' => 'soporte', 'as' => 'soporte.'], function () {
        // DERIVACION DE CONVERSACIONES
            // EL DE ATENCION A CLIENTES DEBE ENTRAR A ESTA PANTALLA
            Route::get('chats/viewer', function () {
                return view('support.logform');
            })->name('index');

            Route::post('chats/viewer', 'BotFwrk\ConversationController@showChatLog')->name('show');
        // DERIVACION DE CONVERSACIONES
    });
});

// DERIVACION DE CONVERSACIONES
    // EL CLIENTE VE ESTA PANTALLA
    Route::get('hotel/soporte/{conversationId}', function ($conversationId) {
        return view('support.support')->with('conversationId', $conversationId);
    });
// DERIVACION DE CONVERSACIONES

app/Http/Controllers/HuespedesController.php
<?php

namespace App\Http\Controllers;

use App\Models\Hotel\Huesped;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;

class HuespedesController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\Http\Response|\Illuminate\View\View
     */
    public function index()
    {
        if (session('selectedHotelId')){
            $huespedes = Huesped::where('hotel_id', session('selectedHotelId'))->get();

            return view('huespedes.index', compact('huespedes'));
        }

        return view('huespedes.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\Http\Response|\Illuminate\View\View
     */
    public function create()
    {
        return view('huespedes.crear');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\RedirectResponse|\Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'nombre' => 'required',
            'apellido' => 'required',
            'email' => 'required|email|unique:huespedes,email', // check if the user is already taken
            'obs' => 'nullable',
        ]);

        try {
            DB::beginTransaction();

            $huesped = new Huesped();

            $huesped->hotel_id = session('selectedHotelId');
            $huesped->nombre = $request->nombre;
            $huesped->apellido = $request->apellido;
            $huesped->email = $request->email;
            if ($request->filled('obs')) {
                $huesped->obs = $request->obs;
            }

            $huesped->save(); // The created_at and updated_at timestamps will automatically be set when the save method is called

            DB::commit();

            \Session::flash("success", "El huésped fue creado exitosamente.");
            return redirect()->route('huespedes.show', [$huesped]);
        } catch (\Exception $e) {
            DB::rollback();
            return redirect()->back()->withErrors($e->getMessage())->withInput();
        }
    }

    /**
     * Display the specified resource.
     *
     * @param Huesped $huesped
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\Http\Response|\Illuminate\View\View
     */
    public function show(Huesped $huesped)
    {
        return view('huespedes.mostrar', compact('huesped'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param Huesped $huesped
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\Http\Response|\Illuminate\View\View
     */
    public function edit(Huesped $huesped)
    {
        return view('huespedes.editar', compact('huesped'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @param Huesped $huesped
     * @return \Illuminate\Http\RedirectResponse|\Illuminate\Http\Response
     */
    public function update(Request $request, Huesped $huesped)
    {
        $this->validate($request, [
            'nombre' => 'required',
            'apellido' => 'required',
            'obs' => 'nullable',
        ]);

        try {
            DB::beginTransaction();

            $huesped->nombre = $request->nombre;
            $huesped->apellido = $request->apellido;
            if ($request->filled('obs')) {
                $huesped->obs = $request->obs;
            } else {
                $huesped->obs = null;
            }

            $huesped->save(); // The created_at and updated_at timestamps will automatically be set when the save method is called

            DB::commit();

            \Session::flash("success", "El huesped fue editado exitosamente.");
            return redirect()->route('huespedes.show', [$huesped]);
        } catch (\Exception $e) {
            DB::rollback();
            return redirect()->back()->withErrors($e->getMessage())->withInput();
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param Huesped $huesped
     * @return \Illuminate\Http\RedirectResponse|\Illuminate\Http\Response
     */
    public function destroy(Huesped $huesped)
    {
        try {
            DB::beginTransaction();

            $huesped->delete();

            DB::commit();

            \Session::flash("success", "El huesped fue borrado exitosamente.");
            return redirect()->route('huespedes.index');
        } catch (\Exception $e) {
            DB::rollback();
            return redirect()->back()->withErrors($e->getMessage());
        }
    }
}

resources/views/huespedes/crear.blade.php
@extends('layouts.project')

@section('htmlheader_title', "{$selectedHotel->nombre} | Crear nuevo huésped")

@section('content_header_title')
    {{ $selectedHotel->nombre }}
@endsection

@section('content_header_description')
    Crear nuevo huésped
@endsection

@section('main-content')
    <div class="row">
        <div class="col-md-10 col-md-offset-1">
            <form action="{{ route('huespedes.store') }}" method="post" id="form_crear" name="form_crear">
                {{ csrf_field() }}
                <div class="form-group">
                    <label for="nombre">Nombres</label>
                    <input type="text" class="form-control" id="nombre" name="nombre" placeholder="Nombre(s)" value="{{ old('nombre') }}">
                </div>
                <div class="form-group">
                    <label for="apellido">Apellidos</label>
                    <input type="text" class="form-control" id="apellido" name="apellido" placeholder="Apellido(s)" value="{{ old('apellido') }}">
                </div>
                <div class="form-group">
                    <label for="email">Email</label>
                    <input type="text" class="form-control" id="email" name="email" placeholder="Email" value="{{ old('email') }}">
                </div>
                <div class="form-group">
                    <label for="obs">Observaciones</label>
                    <textarea class="form-control" rows="3" id="obs" name="obs" placeholder="Observaciones">{{ old('obs') }}</textarea>
                </div>

                <button type="submit" class="btn btn-success btn-lg btn-block">Crear</button>
                <a class="btn btn-info btn-xs btn-block" href="{{ route('huespedes.index') }}" role="button">Retroceder</a>
            </form>
        </div>
    </div>
@endsection

resources/views/huespedes/editar.blade.php
@extends('layouts.project')

@section('htmlheader_title', "{$selectedHotel->nombre} | Editar huésped {$huesped->nombre_completo}")

@section('content_header_title')
    {{ $selectedHotel->nombre }}
@endsection

@section('content_header_description')
    Editar huésped <b>{{ $huesped->nombre_completo }}</b>
@endsection

@section('main-content')
    <div class="row">
        <div class="col-md-10 col-md-offset-1">
            <form action="{{ route('huespedes.update', [$huesped]) }}" method="post" id="form_editar" name="form_editar">
                {{ method_field('PUT') }}
                {{ csrf_field() }}
                <div class="form-group">
                    <label for="nombre">Nombres</label>
                    <input type="text" class="form-control" id="nombre" name="nombre" placeholder="Nombre(s)" value="{{ old('nombre', $huesped->nombre) }}">
                </div>
                <div class="form-group">
                    <label for="apellido">Apellidos</label>
                    <input type="text" class="form-control" id="apellido" name="apellido" placeholder="Apellido(s)" value="{{ old('apellido', $huesped->apellido) }}">
                </div>
                <div class="form-group">
                    <label for="obs">Observaciones</label>
                    <textarea class="form-control" rows="3" id="obs" name="obs" placeholder="Observaciones">{{ old('obs', $huesped->obs) }}</textarea>
                </div>
                <button type="submit" class="btn btn-success btn-block"><i class="fa fa-save"></i> Guardar</button>
                <a class="btn btn-info btn-xs btn-block" href="{{ route('huespedes.show', [$huesped]) }}" role="button">Retroceder</a>
            </form>
        </div>
    </div>
@endsection

resources/views/huespedes/index.blade.php
@extends('layouts.project')

@section('htmlheader_title', 'Huéspedes')

@section('content_header_title')
    Huéspedes
@endsection

@section('content_header_description')
    Listado de huéspedes
@endsection

@section('main-content')
    @include('hoteles.partials.selector_lista_hoteles')

    @if(session('selectedHotelId'))
        <div class="box">
            <div class="box-header with-border">
                <h3 class="box-title">Huéspedes registrados en {{ $selectedHotel->nombre }}</h3>
                <div class="box-tools pull-right">
                    <a class="btn btn-primary" href="{{ route('huespedes.create') }}" role="button" title="Crear registro de huésped"><i class="fa fa-plus-circle"></i> Crear registro de huésped</a>
                </div>
                <!-- /.box-tools -->
            </div>
            <div class="box-body">
                @if (count($huespedes) > 0)
                    <div class="table-responsive">
                        <table id="data_table" name="data_table" class="table table-striped table-hover">
                            <thead>
                            <tr>
                                <th style="text-align: center;">Huésped</th>
                                <th style="text-align: center;">Email</th>
                                <th style="text-align: center;">&nbsp;</th>
                            </tr>
                            </thead>
                            <tbody>
                            @foreach($huespedes as $huesped)
                                <tr style="text-align: center;">
                                    <td style="text-align: center; vertical-align: middle;">
                                        {{ $huesped->nombre_completo }}
                                    </td>
                                    <td style="text-align: center; vertical-align: middle;">
                                        {{ $huesped->email }}
                                    </td>
                                    <td style="text-align: right; vertical-align: middle;">
                                        <div class="btn-group" role="group">
                                            {{-- Ver Registro --}}
                                            <a class="btn btn-xs btn-primary" href="{{ route('huespedes.show', [$huesped]) }}" role="button" title="Ver Detalles"><i class="fa fa-folder-open-o"></i> Ver Detalles</a>
                                            {{-- Editar registro --}}
                                            <a class="btn btn-xs btn-warning" href="{{ route('huespedes.edit', [$huesped]) }}" role="button" title="Editar registro"><i class="fa fa-edit"></i> Editar registro</a>
                                            {{-- Borrar registro --}}
                                            <form class="btn-group" action="{{ route('huespedes.destroy', [$huesped]) }}" method="post" onsubmit="return confirm('Confirma la eliminación de este registro?');">
                                                {{ method_field('DELETE') }}
                                                {{ csrf_field() }}
                                                <button type="submit" class="btn btn-xs btn-danger" title="Borrar registro"><span class="glyphicon glyphicon-trash" aria-hidden="true"></span> Borrar registro</button>
                                            </form>
                                        </div>
                                    </td>
                                </tr>
                            @endforeach
                            </tbody>
                        </table>
                    </div>
                @else
                    <div class="alert alert-warning" role="alert" style="margin-top: 0; margin-bottom: 0;"><b>Aún no se han creado huespedes en el hotel seleccionado</b></div>
                @endif
            </div><!-- /.box-body -->
            <div class="box-footer">
                <a class="btn btn-primary pull-right" href="{{ route('huespedes.create') }}" role="button" title="Crear registro de huésped"><i class="fa fa-plus-circle"></i> Crear registro de huésped</a>
            </div><!-- box-footer -->
        </div><!-- /.box -->
    @else
        <div class="callout callout-info">
            <h4>Aviso</h4>
            <p>Debe seleccionar un hotel para poder ver el listado de huéspedes del mismo</p>
        </div>
    @endif
@endsection

resources/views/huespedes/mostrar.blade.php
@extends('layouts.project')

@section('htmlheader_title', "{$huesped->hotel->nombre} | Detalles del huesped {$huesped->nombre_completo}")

@section('content_header_title')
    {{ $huesped->hotel->nombre }}
@endsection

@section('content_header_description')
    Detalles del huésped {{ $huesped->nombre_completo }}
@endsection

@section('main-content')
    <div class="row">
        <div class="col-md-10 col-md-offset-1">
            <div class="box">
                <div class="box-header with-border">
                    <h3 class="box-title">Datos básicos</h3>
                </div>
                <!-- /.box-header -->
                <div class="box-body">
                    <div class="form-group">
                        <label for="nombre">Nombres</label>
                        <input disabled type="text" class="form-control" id="nombre" name="nombre" value="{{ $huesped->nombre }}">
                    </div>
                    <div class="form-group">
                        <label for="apellido">Apellidos</label>
                        <input disabled type="text" class="form-control" id="apellido" name="apellido" value="{{ $huesped->apellido }}">
                    </div>
                    <div class="form-group">
                        <label for="email">Email</label>
                        <input disabled type="text" class="form-control" id="email" name="email" value="{{ $huesped->email }}">
                    </div>
                    @if( $huesped->obs )
                        <div class="form-group">
                            <label for="obs">Observaciones</label>
                            <textarea disabled class="form-control" rows="3" id="obs" name="obs" placeholder="Observaciones">{{ $huesped->obs }}</textarea>
                        </div>
                    @endif
                </div>
                <!-- /.box-body -->
                <div class="box-footer">
                    <a class="btn btn-warning btn-block" href="{{ route('huespedes.edit', [$huesped]) }}" role="button"><i class="fa fa-edit"></i> Editar</a>
                    <a class="btn btn-info btn-xs btn-block" href="{{ route('huespedes.index') }}" role="button">Retroceder</a>
                </div>
                <!-- box-footer -->
            </div>
            <!-- /.box -->
        </div>
    </div>
@endsection

{{--
@section('scripts')
    @parent
    <script>
        $(function() {

        });
    </script>
@endsection
--}}