routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::get('terminos', function () {
    return view('terminos');
});

Auth::routes();

Route::group(['middleware' => ['auth']], function () {
    Route::get('/home', 'HomeController@index')->name('home');

    Route::group(['prefix' => 'hoteles', 'as' => 'hoteles.'], function () {
        Route::get('/', 'HotelController@index')->name('index');
        Route::get('create', 'HotelController@create')->name('create');
        Route::post('/', 'HotelController@store')->name('store');
        Route::get('{hotel}', 'HotelController@show')->name('show');
        Route::get('{hotel}/edit', 'HotelController@edit')->name('edit');
        Route::put('{hotel}', 'HotelController@update')->name('update');
        Route::delete('{hotel}', 'HotelController@destroy')->name('destroy');

        Route::post('changeWorkingHotel', 'HotelController@changeWorkingHotel')->name('changeworkinghotel');
    });

    Route::group(['prefix' => 'habitaciones', 'as' => 'habitaciones.'], function () {
        Route::get('/', 'HabitacionesController@index')->name('index');
        Route::get('create', 'HabitacionesController@create')->name('create');
        Route::post('/', 'HabitacionesController@store')->name('store');
        Route::get('{habitacion}', 'HabitacionesController@show')->name('show');
        Route::get('{habitacion}/edit', 'HabitacionesController@edit')->name('edit');
        Route::put('{habitacion}', 'HabitacionesController@update')->name('update');
        Route::delete('{habitacion}', 'HabitacionesController@destroy')->name('destroy');
    });

    Route::group(['prefix' => 'huespedes', 'as' => 'huespedes.'], function () {
        Route::get('/', 'HuespedesController@index')->name('index');
        Route::get('create', 'HuespedesController@create')->name('create');
        Route::post('/', 'HuespedesController@store')->name('store');
        Route::get('{huesped}', 'HuespedesController@show')->name('show');
        Route::get('{huesped}/edit', 'HuespedesController@edit')->name('edit');
        Route::put('{huesped}', 'HuespedesController@update')->name('update');
        Route::delete('{huesped}', 'HuespedesController@destroy')->name('destroy');
    });

    Route::group(['prefix' => 'reservas', 'as' => 'reservas.'], function () {
        Route::get('/', 'ReservasController@index')->name('index');
        Route::get('create', 'ReservasController@create')->name('create');
        Route::post('/', 'ReservasController@store')->name('store');
        Route::get('{reserva}', 'ReservasController@show')->name('show');
        Route::get('{reserva}/edit', 'ReservasController@edit')->name('edit');
        Route::put('{reserva}', 'ReservasController@update')->name('update');
        Route::delete('{reserva}', 'ReservasController@destroy')->name('destroy');
    });

    Route::group(['prefix' => 'soporte', 'as' => 'soporte.'], function () {
        // DERIVACION DE CONVERSACIONES
            // EL DE ATENCION A CLIENTES DEBE ENTRAR A ESTA PANTALLA
            Route::get('chats/viewer', function () {
                return view('support.logform');
            })->name('index');

            Route::post('chats/viewer', 'BotFwrk\ConversationController@showChatLog')->name('show');
        // DERIVACION DE CONVERSACIONES
    });
});

// DERIVACION DE CONVERSACIONES
    // EL CLIENTE VE ESTA PANTALLA
    Route::get('hotel/soporte/{conversationId}', function ($conversationId) {
        return view('support.support')->with('conversationId', $conversationId);
    });
// DERIVACION DE CONVERSACIONES

resources/views/hoteles/crear.blade.php
@extends('layouts.project')

@section('htmlheader_title', 'Hoteles')

@section('content_header_title')
    Hoteles
@endsection

@section('content_header_description')
    Crear nuevo hotel
@endsection

@section('main-content')
    <div class="row">
        <div class="col-md-10 col-md-offset-1">
            <form action="{{ route('hoteles.store') }}" method="post" id="form_crear" name="form_crear">
                {{ csrf_field() }}
                <div class="form-group">
                    <label for="nombre">Nombre</label>
                    <input type="text" class="form-control" id="nombre" name="nombre" placeholder="Nombre" value="{{ old('nombre') }}">
                </div>
                <div class="form-group">
                    <label for="direccion">Dirección</label>
                    <input type="text" class="form-control" id="direccion" name="direccion" placeholder="Dirección" value="{{ old('direccion') }}">
                </div>
                <div class="form-group">
                    <label for="telefono">Teléfono</label>
                    <input type="text" class="form-control" id="telefono" name="telefono" placeholder="Teléfono" value="{{ old('telefono') }}">
                </div>
                <div class="form-group">
                    <label for="extension_recepcion">Ext. Recepción</label>
                    <input type="text" class="form-control" id="extension_recepcion" name="extension_recepcion" placeholder="Extensión Recepción" value="{{ old('extension_recepcion') }}">
                </div>
                <div class="form-group">
                    <label for="hora_checkin">Inicio Check-In</label>
                    <input type="text" class="form-control" id="hora_checkin" name="hora_checkin" placeholder="Hora Inicio Check-In" value="{{ old('hora_checkin') }}">
                </div>
                <div class="form-group">
                    <label for="hora_checkout">Max Check-Out</label>
                    <input type="text" class="form-control" id="hora_checkout" name="hora_checkout" placeholder="Hora Máxima Check-Out" value="{{ old('hora_checkout') }}">
                </div>

                <button type="submit" class="btn btn-success btn-lg btn-block">Crear</button>
                <a class="btn btn-info btn-xs btn-block" href="{{ route('hoteles.index') }}" role="button">Retroceder</a>
            </form>
        </div>
    </div>
@endsection

resources/views/hoteles/editar.blade.php
@extends('layouts.project')

@section('htmlheader_title', 'Hoteles')

@section('content_header_title')
    Hoteles
@endsection

@section('content_header_description')
    Editar hotel [<b>{{ $hotel->nombre }}</b>]
@endsection

@section('main-content')
    <div class="row">
        <div class="col-md-10 col-md-offset-1">
            <form action="{{ route('hoteles.update', [$hotel]) }}" method="post" id="form_editar" name="form_editar">
                {{ method_field('PUT') }}
                {{ csrf_field() }}
                <div class="form-group">
                    <label for="nombre">Nombre</label>
                    <input type="text" class="form-control" id="nombre" name="nombre" placeholder="Nombre" value="{{ old('nombre', $hotel->nombre) }}">
                </div>
                <div class="form-group">
                    <label for="direccion">Dirección</label>
                    <input type="text" class="form-control" id="direccion" name="direccion" placeholder="Dirección" value="{{ old('direccion', $hotel->direccion) }}">
                </div>
                <div class="form-group">
                    <label for="telefono">Teléfono</label>
                    <input type="text" class="form-control" id="telefono" name="telefono" placeholder="Teléfono" value="{{ old('telefono', $hotel->telefono) }}">
                </div>
                <div class="form-group">
                    <label for="extension_recepcion">Ext. Recepción</label>
                    <input type="text" class="form-control" id="extension_recepcion" name="extension_recepcion" placeholder="Extensión Recepción" value="{{ old('extension_recepcion', $hotel->extension_recepcion) }}">
                </div>
                <div class="form-group">
                    <label for="hora_checkin">Inicio Check-In</label>
                    <input type="text" class="form-control" id="hora_checkin" name="hora_checkin" placeholder="Hora Inicio Check-In" value="{{ old('hora_checkin', ($hotel->hora_checkin) ? \Carbon\Carbon::createFromTimeString($hotel->hora_checkin)->format('H:i') : '') }}">
                </div>
                <div class="form-group">
                    <label for="hora_checkout">Max Check-Out</label>
                    <input type="text" class="form-control" id="hora_checkout" name="hora_checkout" placeholder="Hora Máxima Check-Out" value="{{ old('hora_checkout', ($hotel->hora_checkout) ? \Carbon\Carbon::createFromTimeString($hotel->hora_checkout)->format('H:i') : '') }}">
                </div>
                <button type="submit" class="btn btn-success btn-block"><i class="fa fa-save"></i> Guardar</button>
                <a class="btn btn-info btn-xs btn-block" href="{{ route('hoteles.show', [$hotel]) }}" role="button">Retroceder</a>
            </form>
        </div>
    </div>
@endsection

resources/views/hoteles/index.blade.php
@extends('layouts.project')

@section('htmlheader_title', 'Hoteles')

@section('content_header_title')
    Hoteles
@endsection

@section('content_header_description')
    Listado de hoteles
@endsection

@section('content_header_extras')
    <a class="btn btn-primary" href="{{ route('hoteles.create') }}" role="button" title="Crear hotel"><i class="fa fa-plus-circle"></i> Crear hotel</a>
@endsection

@section('main-content')
    <div class="box">
        <div class="box-body">
            @if (count($hoteles) > 0)
                <div class="table-responsive">
                    <table id="data_table" name="data_table" class="table table-striped table-hover">
                        <thead>
                            <tr>
                                <th style="text-align: center; min-width: 30em;">Hotel</th>
                                <th style="text-align: center">&nbsp;</th>
                            </tr>
                        </thead>
                        <tbody>
                        @foreach($hoteles as $hotel)
                            <tr style="text-align: center;">
                                <td style="text-align: center; vertical-align: middle;">
                                    {{ $hotel->nombre }}
                                </td>
                                <td style="text-align: center; vertical-align: middle;">
                                    <div class="btn-group" role="group">
                                        {{--Ver Registro--}}
                                        <a class="btn btn-xs btn-primary" href="{{ route('hoteles.show', [$hotel]) }}" role="button" title="Ver Detalles"><i class="fa fa-folder-open-o"></i> Ver Detalles</a>
                                        {{-- Editar registro --}}
                                        <a class="btn btn-xs btn-warning" href="{{ route('hoteles.edit', [$hotel]) }}" role="button" title="Editar registro"><i class="fa fa-edit"></i> Editar registro</a>
                                        {{-- Borrar registro --}}
                                        <form class="btn-group" action="{{ route('hoteles.destroy', [$hotel]) }}" method="post" onsubmit="return confirm('Confirma la eliminación de este registro?');">
                                            {{ method_field('DELETE') }}
                                            {{ csrf_field() }}
                                            <button type="submit" class="btn btn-xs btn-danger" title="Borrar registro"><span class="glyphicon glyphicon-trash" aria-hidden="true"></span> Borrar registro</button>
                                        </form>
                                    </div>
                                </td>
                            </tr>
                        @endforeach
                        </tbody>
                    </table>
                </div>
            @else
                <div class="alert alert-warning" role="alert" style="margin-top: 0; margin-bottom: 0;"><b>Aún no se han creado hoteles en el sistema</b></div>
            @endif
        </div><!-- /.box-body -->
        <div class="box-footer">
            <a class="btn btn-primary pull-right" href="{{ route('hoteles.create') }}" role="button" title="Crear hotel"><i class="fa fa-plus-circle"></i> Crear hotel</a>
        </div><!-- box-footer -->
    </div><!-- /.box -->
@endsection

resources/views/hoteles/mostrar.blade.php
@extends('layouts.project')

@section('htmlheader_title', "Detalles del hotel: $hotel->nombre")

@section('content_header_title')
    {{ $hotel->nombre }}
@endsection

@section('content_header_description')
    Detalles del hotel
@endsection

@section('main-content')
    <div class="row">
        <div class="col-md-10 col-md-offset-1">
            <div class="box">
                <div class="box-header with-border">
                    <h3 class="box-title">Datos básicos</h3>
                </div>
                <!-- /.box-header -->
                <div class="box-body">
                    <div class="form-group">
                        <label for="nombre">Nombre</label>
                        <input disabled type="text" class="form-control" id="nombre" name="nombre" value="{{ $hotel->nombre }}">
                    </div>
                    <div class="form-group">
                        <label for="direccion">Dirección</label>
                        <input disabled type="text" class="form-control" id="direccion" name="direccion" value="{{ $hotel->direccion }}">
                    </div>
                    <div class="form-group">
                        <label for="telefono">Teléfono</label>
                        <input disabled type="text" class="form-control" id="telefono" name="telefono" value="{{ $hotel->telefono }}">
                    </div>
                    <div class="form-group">
                        <label for="extension_recepcion">Ext. Recepción</label>
                        <input disabled type="text" class="form-control" id="extension_recepcion" name="extension_recepcion" value="{{ $hotel->extension_recepcion }}">
                    </div>
                    @isset( $hotel->hora_checkin )
                        <div class="form-group">
                            <label for="hora_checkin">Inicio Check-In</label>
                            <input disabled type="text" class="form-control" id="hora_checkin" name="hora_checkin" value="{{ \Carbon\Carbon::createFromTimeString($hotel->hora_checkin)->format('H:i') }}">
                        </div>
                    @endisset
                    @isset( $hotel->hora_checkout )
                    <div class="form-group">
                        <label for="hora_checkout">Max Check-Out</label>
                        <input disabled type="text" class="form-control" id="hora_checkout" name="hora_checkout" value="{{ \Carbon\Carbon::createFromTimeString($hotel->hora_checkout)->format('H:i') }}">
                    </div>
                    @endisset
                </div>
                <!-- /.box-body -->
                <div class="box-footer">
                    <a class="btn btn-warning btn-block" href="{{ route('hoteles.edit', [$hotel]) }}" role="button"><i class="fa fa-edit"></i> Editar</a>
                    <a class="btn btn-info btn-xs btn-block" href="{{ route('hoteles.index') }}" role="button">Retroceder</a>
                </div>
                <!-- box-footer -->
            </div>
            <!-- /.box -->
        </div>
    </div>
@endsection

{{--
@section('scripts')
    @parent
    <script>
        $(function() {

        });
    </script>
@endsection
--}}